version: '3'

volumes:
  static:
  media:
  postgres_data:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
        - postgres_data:/var/lib/postgresql/data/

  backend:
    image: nikvf/foodgram_backend
    env_file: .env
    depends_on:
        - db
    volumes:
        - static:/app/static
        - media:/app/media

  frontend:
    image: nikvf/foodgram_frontend
    depends_on:
        - backend
    command: cp -r /app/build/. /frontend_static/
    volumes:
        - static:/frontend_static

  nginx:
    image: nikvf/foodgram_gateway
    env_file: .env
    depends_on:
        - frontend
    ports:
        - "8080:80"
    volumes:
        # - ./nginx.conf:/etc/nginx/conf.d/default.conf
        # - static:/usr/share/nginx/html/
        # - ../docs/:/usr/share/nginx/html/api/docs/
        - static:/static
        - media:/media