version: '3'

volumes:
  static:
  media:
  postgres_data:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
        - postgres_data:/var/lib/postgresql/data/

  backend:
    image: nikvf/foodgram_backend
    env_file: .env
    depends_on:
        - db
    volumes:
        - static:/app/backend_static/
        - media:/app/media/

  frontend:
    image: nikvf/foodgram_frontend
    depends_on:
        - backend
    volumes:
        - static:/app/result_build/

  nginx:
    image: nikvf/foodgram_gateway
    env_file: .env
    depends_on:
        - frontend
    ports:
        - '8080:80'
    volumes:
        - static:/var/html/backend_static/
        - media:/var/html/media/
        - static:/usr/share/nginx/html/
