version: '3'

volumes:
  static:
  media:
  postgres_data:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
        - postgres_data:/var/lib/postgresql/data/

  backend:
    image: nikvf/foodgram_backend
    env_file: .env
    # depends_on:
    #     - db
    volumes:
        - static:/app/static/
        - media:/app/media/

  frontend:
    image: nikvf/foodgram_frontend
    depends_on:
        - backend
    command: cp -r /app/build/. /frontend_static/
    volumes:
        - static:/frontend_static

  nginx:
    image: nikvf/foodgram_gateway
    env_file: .env
    depends_on:
        - frontend
    ports:
        - '8080:80'
    volumes:
        - static:/var/html/static/
        - media:/var/html/media/